"""Nueva migración después de sincronizar

Revision ID: 7e0d3d75d93b
Revises: 585547282ab3
Create Date: 2025-05-28 20:00:58.545003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0d3d75d93b'
down_revision = '585547282ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrevistas',
    sa.Column('entId', sa.Integer(), nullable=False),
    sa.Column('entFecha', sa.Date(), nullable=True),
    sa.Column('entTitular', sa.String(length=250), nullable=True),
    sa.Column('entSubtitulo', sa.String(length=250), nullable=True),
    sa.Column('entCuerpoEntrevista', sa.Text(), nullable=True),
    sa.Column('entImagen', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('entId')
    )
    op.create_table('eventos',
    sa.Column('evId', sa.Integer(), nullable=False),
    sa.Column('evFecha', sa.Date(), nullable=True),
    sa.Column('evPoblacion', sa.String(length=100), nullable=True),
    sa.Column('evProvincia', sa.String(length=100), nullable=True),
    sa.Column('evLugar', sa.String(length=200), nullable=True),
    sa.Column('evHora', sa.String(length=10), nullable=True),
    sa.Column('evEntradas', sa.String(length=200), nullable=True),
    sa.Column('evObservaciones', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('evId')
    )
    op.create_table('sorteos',
    sa.Column('sorId', sa.Integer(), nullable=False),
    sa.Column('sorNombre', sa.String(length=250), nullable=True),
    sa.Column('sorDescripcion', sa.Text(), nullable=True),
    sa.Column('sorFechaInicio', sa.Date(), nullable=True),
    sa.Column('sorFechaFin', sa.Date(), nullable=True),
    sa.Column('sorImagen', sa.String(length=250), nullable=True),
    sa.Column('sorResultado', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('sorId')
    )
    op.create_table('usuarios',
    sa.Column('usId', sa.Integer(), nullable=False),
    sa.Column('usEmail', sa.String(length=120), nullable=False),
    sa.Column('usPassword', sa.String(length=250), nullable=False),
    sa.Column('usUsername', sa.String(length=120), nullable=False),
    sa.Column('usNombre', sa.String(length=250), nullable=True),
    sa.Column('usApellidos', sa.String(length=250), nullable=True),
    sa.Column('usTelefono', sa.String(length=9), nullable=True),
    sa.Column('usProvincia', sa.String(length=50), nullable=True),
    sa.Column('usPueblo', sa.String(length=100), nullable=True),
    sa.Column('usDireccion', sa.String(length=200), nullable=True),
    sa.Column('usRol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('usId')
    )
    op.create_table('participaciones',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sorteo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sorteo_id'], ['sorteos.sorId'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usId'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'sorteo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participaciones')
    op.drop_table('usuarios')
    op.drop_table('sorteos')
    op.drop_table('eventos')
    op.drop_table('entrevistas')
    # ### end Alembic commands ###
