"""Agrego campo user_uid a Usuario

Revision ID: ac24e78fe1f0
Revises: 7e0d3d75d93b
Create Date: 2025-06-11 12:47:25.311548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac24e78fe1f0'
down_revision = '7e0d3d75d93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('user_uid',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.create_unique_constraint(None, ['user_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_uid',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
