"""Descripción de los cambios en el modelo

Revision ID: d946dd0aa0a8
Revises: d9e326371989
Create Date: 2024-12-22 21:07:40.462148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd946dd0aa0a8'
down_revision = 'd9e326371989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('usuarios_usEmail_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('usuarios_usEmail_key', ['usEmail'])

    # ### end Alembic commands ###
